### ISSUE TITLE
Latest image (2.7.4) not working

### ISSUE THREAD

**Issue by jjvdgeer** [etechonomy/joplin-server#1]
I used to use the florider89 joplin image for my armv7 NAS, but that it took a while for the last version to appear there, so I looked around and found that this one was updated and seemed otherwise very similar, so I switched to this one.

Yesterday a new version was released, 2.7.4. However after installing it it did not work and investigating, I found that it gave me format errors. This usually mean that I've used the wrong platform, but after some investigation it seems not to be that, but I'm not really sure where the problem is. However, looking at the [tags](https://hub.docker.com/r/etechonomy/joplin-server/tags) it seems that the latest release is a lot smaller than earlier releases (about 300MB vs about 1GB). Any suggestions what the problem is here?

Thanks.

**Comment by etho201** [comment]
I'm experiencing the same issue as I run Joplin Server on my Raspberry Pi. It doesn't have anything to do with the size of the image though -- as the upstream Joplin Server container image for 2.7.4 has also dropped in size. Also, I tried running the x86_64 version of `etechonomy/joplin-server:2.7.4` on my laptop and that one works fine.

Upon further investigation, I am pretty sure I see the issue. In the new Dockerfile.server, there is this line:
```
# Download the init tool Tini and make it executable for use in the final image
ADD https://github.com/krallin/tini/releases/download/v0.19.0/tini-static /tini
```
This is a hard reference to the amd64 version of tini, which isn't compatible with arm64. Tini has arm64 builds though... So this should be an easy fix. I'm just trying to find the best way to do that without making drastic changes to the upstream Dockerfile.

**Comment by etho201** [comment]
I fixed the issue (with https://github.com/etechonomy/joplin-server/commit/c2bfa83253593ce085b2f4d1f7d832a449036d9f). If you pull the image down again it should work.

**Comment by jjvdgeer** [comment]
Thanks, confirmed, it works fine now.
