### ISSUE TITLE
Unable to save files to mounted drive

### ISSUE THREAD

**Issue by doobes** [etechonomy/joplin-server#13]
Well,

I've beat my head on this for a week now.

I've run through the setup process so many times that I've bumped into the LetsEncrypt weekly cert limit.

I cannot get the server to use a mounted drive for storage. I've tried a symlink to the folder, nothing works.

I always get error: "could not change permissions of directory "/var/lib/postgresql/data": Operation not supported"

So, for now I'm syncing locally.

Unfortunately it's not going to take long to fill up this sd card at 64gb.

Any ideas on how to move forward with a mounted external storage drive?

It's a Synology NAS that I've got mounted via CIFS.

That part works just fine.

Is this, perhaps a permission issue?

My compose-docker file looks like this:

```
services:
	db:
		restart: unless-stopped
		image: postgres:latest
	ports:
		- "5432:5432"
	volumes:
		- /home/joplin/data/:/var/lib/postgresql/data
	environment:
		- POSTGRES_PASSWORD=mypassword
		- POSTGRES_USER=joplin
		- POSTGRES_DB=joplin
	app:
	environment:
		- APP_BASE_URL=https://my-server.com/joplin
		- APP_PORT=22300
		- POSTGRES_PASSWORD=mypassword
		- POSTGRES_DATABASE=joplin
		- POSTGRES_USER=joplin
		- POSTGRES_PORT=5432
		- POSTGRES_HOST=db
		- DB_CLIENT=pg
		restart: unless-stopped
		image: etechonomy/joplin-server:latest
	ports:
		- "22300:22300"
	depends_on:
		- db
```

where /home/joplin/data is a symbolic link to /mnt/Joplin

I tried it with /mnt/joplin as the target to same effect.

It weird as the /data folder wasn't there before the process started, but was created in the process.

I've played around enough to confirm it's a bug.  Is there a work around? Can it be fixed? 

Thanks,

**Comment by etho201** [comment]
I've had no issues using with an external mount. I see you closed this already. Do you mind sharing what you did to fix your issue?

**Comment by doobes** [comment]
It's not fixed.

etechonomy asked me to close the ticket because it's not a docker thing.

Can you tell me how you defined your external mount?

I'm guessing that this is permissions related.

cheers

**Comment by etho201** [comment]
Where is your external storage mounted? Take a look at this line:

```bash
volumes:
  - /home/joplin/data/:/var/lib/postgresql/data
```

I doubt your external storage is here: `/home/joplin/data/` ?

You want to change the left side to the location of your external storage. For example:

```
volumes:
  - /mnt/hdd1/docker/volumes/joplin-data:/var/lib/postgresql/data
```

**Comment by doobes** [comment]
If I mounted the storage using CIFS, it would fail. Changing the mount to NFS, it works. 

Go figure.
